from __future__ import annotations

from multi_agent_sql_assistant.agents.generator import SQLGeneratorAgent
from multi_agent_sql_assistant.database import DatabaseSchema
from multi_agent_sql_assistant.llm import LLMGenerationError
from multi_agent_sql_assistant.types import QueryPlan, QuerySpec


class FakeSpecLLMSuccess:
    def generate_spec(self, question: str, plan: QueryPlan, schema: DatabaseSchema) -> QuerySpec:
        return QuerySpec(
            target_table="orders",
            select=["*"],
            limit=plan.limit,
            mode="count",
            reasoning="generated by fake llm",
        )


class FakeSpecLLMFailure:
    def generate_spec(self, question: str, plan: QueryPlan, schema: DatabaseSchema) -> QuerySpec:
        raise LLMGenerationError("synthetic failure")


def test_generator_uses_llm_spec_when_available() -> None:
    schema = DatabaseSchema(tables={"orders": ["id", "amount"]})
    plan = QueryPlan(intent="count", table_hint=None, limit=20, notes=[])
    generator = SQLGeneratorAgent(llm_client=FakeSpecLLMSuccess())

    spec = generator.generate_spec("How many orders?", plan=plan, schema=schema)

    assert spec.target_table == "orders"
    assert spec.mode == "count"
    assert spec.reasoning.startswith("llm spec generation")


def test_generator_falls_back_to_heuristic_spec_when_llm_fails() -> None:
    schema = DatabaseSchema(tables={"orders": ["id", "amount"]})
    plan = QueryPlan(intent="count", table_hint=None, limit=20, notes=[])
    generator = SQLGeneratorAgent(llm_client=FakeSpecLLMFailure())

    spec = generator.generate_spec("How many orders?", plan=plan, schema=schema)

    assert spec.target_table == "orders"
    assert spec.mode == "count"
    assert spec.reasoning.startswith("heuristic spec generation")


def test_generator_generate_keeps_legacy_sql_compatibility() -> None:
    schema = DatabaseSchema(tables={"orders": ["id", "amount"]})
    plan = QueryPlan(intent="count", table_hint=None, limit=20, notes=[])
    generator = SQLGeneratorAgent(llm_client=FakeSpecLLMSuccess())

    query = generator.generate("How many orders?", plan=plan, schema=schema)

    assert query.selected_table == "orders"
    assert "COUNT" in query.sql.upper()
