from __future__ import annotations

from multi_agent_sql_assistant.agents.generator import SQLGeneratorAgent
from multi_agent_sql_assistant.database import DatabaseSchema
from multi_agent_sql_assistant.llm import LLMGenerationError
from multi_agent_sql_assistant.types import GeneratedQuery, QueryPlan


class FakeLLMSuccess:
    def generate(self, question: str, plan: QueryPlan, schema: DatabaseSchema) -> GeneratedQuery:
        return GeneratedQuery(
            sql='SELECT COUNT(*) AS total_count FROM "orders"',
            selected_table="orders",
            reasoning="generated by fake llm",
        )


class FakeLLMFailure:
    def generate(self, question: str, plan: QueryPlan, schema: DatabaseSchema) -> GeneratedQuery:
        raise LLMGenerationError("synthetic failure")


def test_generator_uses_llm_when_available() -> None:
    schema = DatabaseSchema(tables={"orders": ["id", "amount"]})
    plan = QueryPlan(intent="count", table_hint=None, limit=20, notes=[])
    generator = SQLGeneratorAgent(llm_client=FakeLLMSuccess())

    query = generator.generate("How many orders?", plan=plan, schema=schema)

    assert query.selected_table == "orders"
    assert "COUNT" in query.sql.upper()
    assert query.reasoning.startswith("llm generation")


def test_generator_falls_back_when_llm_fails() -> None:
    schema = DatabaseSchema(tables={"orders": ["id", "amount"]})
    plan = QueryPlan(intent="count", table_hint=None, limit=20, notes=[])
    generator = SQLGeneratorAgent(llm_client=FakeLLMFailure())

    query = generator.generate("How many orders?", plan=plan, schema=schema)

    assert query.selected_table == "orders"
    assert "COUNT" in query.sql.upper()
    assert "intent" in query.reasoning
